CREATE TABLE IF NOT EXISTS genre (
	genre_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(50)
);

CREATE TABLE IF NOT EXISTS rating (
	rating_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar(20)
);

CREATE TABLE IF NOT EXISTS films (
	film_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar,
	description varchar(200),
	release_date date,
	duration integer,
	rating_id integer REFERENCES rating (rating_id)
);

CREATE TABLE IF NOT EXISTS film_genre (
	film_id INTEGER REFERENCES films (film_id),
	genre_id INTEGER REFERENCES genre (genre_id)
);

CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar,
	login varchar,
	name varchar,
	birthday date
);

CREATE TABLE IF NOT EXISTS film_likes (
	film_id integer REFERENCES films (film_id),
	user_id integer REFERENCES users (user_id)
);

CREATE TABLE IF NOT EXISTS friendship (
	user_id integer REFERENCES users (user_id),
	friend_id integer REFERENCES users (user_id),
	friend_confirm boolean
);